//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entitity_Oto_Galeri_Programı
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLARAÇLAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLARAÇLAR()
        {
            this.TBLSOZLESME = new HashSet<TBLSOZLESME>();
        }
    
        public int AraçNo { get; set; }
        public Nullable<int> AraçFiyat { get; set; }
        public string AraçMarka { get; set; }
        public Nullable<int> AraçModel { get; set; }
        public string AraçTip { get; set; }
        public string AraçVites { get; set; }
        public string AraçPaket { get; set; }
        public string AraçRenk { get; set; }
        public Nullable<int> AraçŞubeNo { get; set; }
        public string AraçDurum { get; set; }
        public string AraçFoto { get; set; }
    
        public virtual TBLŞUBELER TBLŞUBELER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSOZLESME> TBLSOZLESME { get; set; }
    }
}
