//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entitity_Oto_Galeri_Programı
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKAYITLAR
    {
        public int KayıtID { get; set; }
        public string Kullanıcıİsim { get; set; }
        public string KullanıcıSoyisim { get; set; }
        public Nullable<int> KullanıcıNo { get; set; }
    
        public virtual TBLKULLANICILAR TBLKULLANICILAR { get; set; }
    }
}
