//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entitity_Oto_Galeri_Programı
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMÜSTERİLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLMÜSTERİLER()
        {
            this.TBLSOZLESME = new HashSet<TBLSOZLESME>();
        }
    
        public int MüşteriNo { get; set; }
        public string MüşteriAd { get; set; }
        public string MüşteriSoyad { get; set; }
        public string MüşteriMail { get; set; }
        public string MüşteriTelefon { get; set; }
        public string MüşteriAdres { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSOZLESME> TBLSOZLESME { get; set; }
    }
}
