//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entitity_Oto_Galeri_Programı
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPERSONELLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLPERSONELLER()
        {
            this.TBLSOZLESME = new HashSet<TBLSOZLESME>();
        }
    
        public int PersonelNo { get; set; }
        public string PersonelAd { get; set; }
        public string PersonelSoyad { get; set; }
        public Nullable<int> PersonelYas { get; set; }
        public string PersonelTc { get; set; }
        public string PersonelMail { get; set; }
        public string PersonelTelefon { get; set; }
        public string PersonelAdres { get; set; }
        public Nullable<int> PersonelŞubeNo { get; set; }
    
        public virtual TBLŞUBELER TBLŞUBELER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSOZLESME> TBLSOZLESME { get; set; }
    }
}
