//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entitity_Oto_Galeri_Programı
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSOZLESME
    {
        public int SözleşmeNo { get; set; }
        public Nullable<int> MüşteriNo { get; set; }
        public Nullable<int> PersonelNo { get; set; }
        public Nullable<int> AraçNo { get; set; }
        public Nullable<int> ŞubeNo { get; set; }
        public string İslem { get; set; }
        public string ToplamFiyat { get; set; }
        public string QRKod { get; set; }
    
        public virtual TBLARAÇLAR TBLARAÇLAR { get; set; }
        public virtual TBLMÜSTERİLER TBLMÜSTERİLER { get; set; }
        public virtual TBLPERSONELLER TBLPERSONELLER { get; set; }
        public virtual TBLŞUBELER TBLŞUBELER { get; set; }
    }
}
