//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entitity_Oto_Galeri_Programı
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLŞUBELER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLŞUBELER()
        {
            this.TBLARAÇLAR = new HashSet<TBLARAÇLAR>();
            this.TBLPERSONELLER = new HashSet<TBLPERSONELLER>();
            this.TBLSOZLESME = new HashSet<TBLSOZLESME>();
        }
    
        public int ŞubeNo { get; set; }
        public string ŞubeAdı { get; set; }
        public Nullable<int> ŞubePersoneller { get; set; }
        public string ŞubeAdresi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLARAÇLAR> TBLARAÇLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPERSONELLER> TBLPERSONELLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSOZLESME> TBLSOZLESME { get; set; }
    }
}
